# Copyright (C) 2024 YourName
#
name: OpenWrt Custom Builder

on:
  workflow_dispatch:
    inputs:
      kernel:
        description: 'Kernel Version (ex. openwrt-24.10, openwrt-23.05)'
        required: true
        default: 'openwrt-24.10'
        type: string
      rootfs_size:
        description: "ROOTFS Size, min 640 (756, 1024, 2048, etc)"
        required: true
        default: '1024'
        type: string
      fwinfo:
        description: 'Firmware Information'
        required: true
        default: 'Custom OpenWrt Build'
        type: string

jobs: 
  build_firmware:
    permissions:
      contents: write
    name: Build OpenWrt Firmware
    runs-on: ubuntu-latest
    steps:
      
      - name: Checkout OpenWrt Repository
        uses: actions/checkout@v4
        with:
          repository: openwrt/openwrt
          ref: openwrt-${{ inputs.kernel }}

      - name: Install Dependencies
        run: |
          sudo apt-get update
          sudo apt-get -y install build-essential libncurses5-dev zlib1g-dev gawk flex quilt git wget libssl-dev xsltproc libxml-parser-perl mercurial bzr ecj cvs unzip python3 python3-pip python3-setuptools python3-yaml python3-jinja2 rsync subversion libelf-dev cmake ninja-build
          sudo pip3 install pyyaml jinja2

      - name: Update Feeds
        run: |
          ./scripts/feeds update -a
          ./scripts/feeds install -a

      - name: Configure Build Environment
        run: |
          cp .config.example .config
          sed -i 's/^# CONFIG_TARGET_x86_64_generic is not set/CONFIG_TARGET_x86_64_generic=y/' .config
          sed -i 's/^# CONFIG_TARGET_x86_64 is not set/CONFIG_TARGET_x86_64=y/' .config
          sed -i 's/^# CONFIG_TARGET_x86 is not set/CONFIG_TARGET_x86=y/' .config
          sed -i 's/^# CONFIG_TARGET_IMAGES_GZIP is not set/CONFIG_TARGET_IMAGES_GZIP=y/' .config
          sed -i 's/^# CONFIG_TARGET_IMAGES_PAD is not set/CONFIG_TARGET_IMAGES_PAD=y/' .config
          sed -i 's/^# CONFIG_TARGET_IMAGES_PAD_EXTRA is not set/CONFIG_TARGET_IMAGES_PAD_EXTRA=y/' .config
          sed -i 's/^# CONFIG_TARGET_IMAGES_PAD_TO is not set/CONFIG_TARGET_IMAGES_PAD_TO=${{ inputs.rootfs_size }}M/' .config

      - name: Add Custom Packages
        run: |
          echo 'CONFIG_PACKAGE_luci-theme-argon=y' >> .config
          echo 'CONFIG_PACKAGE_ttyd=y' >> .config
          echo 'CONFIG_PACKAGE_docker=y' >> .config
          echo 'CONFIG_PACKAGE_docker-compose=y' >> .config
          echo 'CONFIG_PACKAGE_miniupnpd=y' >> .config
          echo 'CONFIG_PACKAGE_luci-app-kms=y' >> .config
          echo 'CONFIG_PACKAGE_luci-app-passwall=y' >> .config
          echo 'CONFIG_PACKAGE_luci-app-adguardhome=y' >> .config
          echo 'CONFIG_PACKAGE_luci-app-mosdns=y' >> .config
          echo 'CONFIG_PACKAGE_luci-app-alist=y' >> .config
          echo 'CONFIG_PACKAGE_luci-app-openclash=y' >> .config
          echo 'CONFIG_PACKAGE_luci-app-autotimeset=y' >> .config
          echo 'CONFIG_PACKAGE_luci-app-store=y' >> .config
          echo 'CONFIG_PACKAGE_kmod-usb-core=y' >> .config
          echo 'CONFIG_PACKAGE_kmod-usb2=y' >> .config
          echo 'CONFIG_PACKAGE_kmod-usb-storage=y' >> .config
          echo 'CONFIG_PACKAGE_kmod-usb-net=y' >> .config
          echo 'CONFIG_PACKAGE_kmod-usb-net-asix=y' >> .config
          echo 'CONFIG_PACKAGE_kmod-usb-net-rndis=y' >> .config
          echo 'CONFIG_PACKAGE_kmod-usb-net-cdc-ether=y' >> .config
          echo 'CONFIG_PACKAGE_kmod-pci=y' >> .config
          echo 'CONFIG_PACKAGE_kmod-pci-generic=y' >> .config
          echo 'CONFIG_PACKAGE_kmod-pci-uhci=y' >> .config
          echo 'CONFIG_PACKAGE_kmod-pci-ohci=y' >> .config
          echo 'CONFIG_PACKAGE_kmod-pci-ehci=y' >> .config
          echo 'CONFIG_PACKAGE_kmod-pci-xhci=y' >> .config
          echo 'CONFIG_PACKAGE_kmod-usb-serial=y' >> .config
          echo 'CONFIG_PACKAGE_kmod-usb-serial-option=y' >> .config
          echo 'CONFIG_PACKAGE_kmod-usb-serial-wwan=y' >> .config
          echo 'CONFIG_PACKAGE_kmod-usb-net-ipheth=y' >> .config
          echo 'CONFIG_PACKAGE_kmod-usb-net-qmi-wwan=y' >> .config
          echo 'CONFIG_PACKAGE_kmod-usb-net-rndis=y' >> .config
          echo 'CONFIG_PACKAGE_kmod-usb-net-cdc-ether=y' >> .config
          echo 'CONFIG_PACKAGE_kmod-usb-net-cdc-acm=y' >> .config
          echo 'CONFIG_PACKAGE_kmod-usb-net-cdc-mbim=y' >> .config
          echo 'CONFIG_PACKAGE_kmod-usb-net-cdc-wdm=y' >> .config
          echo 'CONFIG_PACKAGE_kmod-usb-net-cdc-ncm=y' >> .config
          echo 'CONFIG_PACKAGE_kmod-usb-net-cdc-subset=y' >> .config
          echo 'CONFIG_PACKAGE_kmod-usb-net-dm9601=y' >> .config
          echo 'CONFIG_PACKAGE_kmod-usb-net-gl620a=y' >> .config
          echo 'CONFIG_PACKAGE_kmod-usb-net-hso=y' >> .config
          echo 'CONFIG_PACKAGE_kmod-usb-net-kaweth=y' >> .config
          echo 'CONFIG_PACKAGE_kmod-usb-net-kalmia=y' >> .config
          echo 'CONFIG_PACKAGE_kmod-usb-net-kaweth=y' >> .config

      - name: Modify LAN IP Address
        run: |
          echo 'uci set network.lan.ipaddr="192.168.6.1"' >> files/etc/uci-defaults/99_custom_defaults

      - name: Add Author Information
        run: |
          echo 'echo "Compiled by YourName" > /etc/openwrt_release_custom' >> files/etc/uci-defaults/99_custom_defaults

      - name: Build Firmware
        run: |
          make -j$(nproc) V=s

      - name: Create Artifact Directory
        run: |
          mkdir -p artifact
          cp bin/targets/x86/64/*.img.gz artifact/

      - name: Upload Artifact
        uses: actions/upload-artifact@v4
        with:
          name: openwrt_firmware
          path: artifact/*

      - name: Upload Release Asset
        uses: svenstaro/upload-release-action@v2
        with:
          repo_token: ${{ secrets.GITHUB_TOKEN }}
          file: artifact/*
          tag: v${{ inputs.kernel }}
          file_glob: true
          overwrite: true
          body: |
            ## OpenWRT Release for x86_64 devices
            ULO-Builder Release from Github Workflow
            ### OpenWrt Image Information
            - Firmware Details : 
              - Devices type : x86_64
              - Kernel version : ${{ inputs.kernel }}
              - ROOTFS Size : ${{ inputs.rootfs_size }}M
            - Firmware Information : 
              - ${{ inputs.fwinfo }}
            - Compiled by : 04543473
            - LAN IP Address : 192.168.6.1
